# Copyright 2022 Jody Sankey
# This software may be modified and distributed under the terms
# of the MIT license. See the LICENCE.md file for details.

name: nmea_dashboard
description: A viewer for real time NMEA network data.

publish_to: 'none'

version: 0.4.0+22

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  async: ^2.11.0
  cupertino_icons: ^1.0.8
  collection: ^1.18.0
  flutter_markdown_plus: ^1.0.6
  logging: ^1.3.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  shared_preferences: ^2.3.2
  sprintf: ^7.0.0
  package_info_plus: ^9.0.0
  provider: ^6.1.2
  udp: ^5.0.3
  clock: ^1.1.2
  fake_async: ^1.3.3
  wakelock_plus: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # build_runner et json_serializable doivent être ici pour la portabilité
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  flutter_lints: ^5.0.0
  test: ^1.25.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Digital
      fonts:
        - asset: fonts/DigitalNormal.otf
    - family: FredokaOne
      fonts:
        - asset: fonts/FredokaOne-Regular.ttf
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
    - family: Kanit
      fonts:
        - asset: fonts/Kanit-Regular.ttf
    - family: Lexend
      fonts:
        - asset: fonts/Lexend-Regular.ttf
    - family: Manrope
      fonts:
        - asset: fonts/Manrope-Regular.ttf
    - family: Orbitron
      fonts:
        - asset: fonts/Orbitron-Regular.ttf
    - family: Sniglet
      fonts:
        - asset: fonts/Sniglet-Regular.ttf
